# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-06 15:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20160606_2305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='liked',
            new_name='likes',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='liked',
            new_name='likes',
        ),
    ]
